name: Build PassKey Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出源码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          apt update
          apt install -y wget unzip nodejs npm openjdk-17-jdk

      - name: 安装 pwa2apk
        run: npm install -g @bubblewrap/cli

      - name: 进入网页源码目录
        working-directory: ./V2.1.1_WEB
        run: |
          bubblewrap init --manifest ./manifest.json --package com.wisewang1013.passkey
          bubblewrap build

      - name: 上传APK成品
        uses: actions/upload-artifact@v4
        with:
          name: PassKey-APK
          path: ./V2.1.1_WEB/app-bundle/*.apk
